apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob-with-dotnet
spec:
  schedule: "*/5 * * * *" # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mycronjob-with-dotnet
            image: lfgrando/kube-cronjob-dotnet:latest
          restartPolicy: OnFailure