apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob-with-dotnet
spec:
  schedule: "*/1 * * * *" # Runs every 1 minutes
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: mycronjob-with-dotnet
            image: lfgrando/kube-cronjob-dotnet:latest
          restartPolicy: OnFailure